import{a as L,S as p,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&i(y)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const w="11370735-3d6e0314cf2e59c2293396bf4",S="https://pixabay.com/api/";async function m(s,e=1){try{return(await L.get(S,{params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(r){return console.error("Помилка при запиті Pixabay:",r),null}}const g=document.querySelector(".gallery");let n=new p(".gallery a");function h(s){const e=s.map(r=>`
    <li class="gallery__item">
      <a href="${r.largeImageURL}" class="gallery__link">
        <img src="${r.webformatURL}" alt="${r.tags}" class="gallery__image" />
      </a>
      <div class="gallery__info">
        <p class="gallery__info-item"><b>Likes</b> ${r.likes}</p>
        <p class="gallery__info-item"><b>Views</b> ${r.views}</p>
        <p class="gallery__info-item"><b>Comments</b> ${r.comments}</p>
        <p class="gallery__info-item"><b>Downloads</b> ${r.downloads}</p>
      </div>
    </li>
  `).join("");g.insertAdjacentHTML("beforeend",e),n.refresh(),n?n.refresh():n=new p(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){g.innerHTML=""}function b(){document.querySelector(".loader-backdrop").classList.remove("is-hidden")}function c(){document.querySelector(".loader-backdrop").classList.add("is-hidden")}let d=1,l="",f=0;const _=document.querySelector(".form"),q=_.querySelector('input[name="search-text"]'),u=document.querySelector(".load-more");_.addEventListener("submit",async function(s){if(s.preventDefault(),l=q.value.trim(),!l){a.error({title:"Error",message:"Введіть пошуковий запит!",position:"topRight"});return}v(),u.style.display="none",b(),d=1;try{const e=await m(l,d);if(c(),!e||e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f=e.totalHits,h(e.hits),e.hits.length<f&&(u.style.display="block")}catch{c(),a.error({title:"Error",message:"Щось пішло не так. Спробуйте пізніше.",position:"topRight"})}});u.addEventListener("click",async function(){d+=1,b();try{const s=await m(l,d);c(),h(s.hits),document.querySelectorAll(".gallery img").length>=f&&(u.style.display="none",a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const i=document.querySelector(".gallery__item").getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}catch{c(),a.error({title:"Error",message:"Щось пішло не так. Спробуйте пізніше.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
